# Dependencies
markdown:         redcarpet
highlighter:      true

# Permalinks
permalink:        pretty

# Setup
title:            Ben Marx
tagline:          ''
description:      ''
url:              http://bgmarx.com

author:
  name:           'Ben Marx'
  url:            ''

paginate:         5

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/bgmarx.com/bgmarx.github.io
